### ISSUE TITLE
Compile error for stri_time_zone.cpp on libicu 50.1.2

### ISSUE THREAD

**Issue by jeroenooms** [Rexamine/stringi#166]
The `stri_time_zone.cpp` is the only file that fails to compile on CentOS 7 (libicu 50.1.2). Everything else compiles out of the box. It would be really cool if this can be fixed so that stringi can link against system libicu on CentOS 7.

```
g++ -m64 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c stri_time_zone.cpp -o stri_time_zone.o
stri_time_zone.cpp: In function ‘SEXPREC* stri_timezone_info(SEXP, SEXP, SEXP)’:
stri_time_zone.cpp:220:4: error: ‘getWindowsID’ is not a member of ‘icu_50::TimeZone’
    TimeZone::getWindowsID(val_ID, val_windows, status);
    ^
```

**Comment by gagolews** [comment]
Yes, it fails, because this fun is from ICU>=52. Current devel branch of string **requires** icu >= 52

I'll look at this later and think about downgrading the requirements

**Comment by jeroenooms** [comment]
50 is fine, that is pretty mainstream. I think `getWindowsID` is the only call that requires 0.52?

**Comment by jeroenooms** [comment]
Any chance you can look into this? It would be really cool if we can take advantage of system ICU on redhat/centos 7 deployments. Centos 6 has libicu icu-4.2.1 so that is probably out of the question, but it shouldn't be hard to get it to work on Centos 7.

**Comment by gagolews** [comment]
OK, I'll build ICU 50 and see what I can do with that.

```
#if U_ICU_VERSION_MAJOR_NUM>=50
...
#endif
```

**Comment by jeroenooms** [comment]
Thanks! Appreciate it. I'll give a try on a vm once you're done, see if it works.

**Comment by gagolews** [comment]
@jeroenooms OK, now icu4c>=50 is required, please confirm if all OK

**Comment by jeroenooms** [comment]
Yay I think it works. Thanks this is a big improvement.
